{% set name = "pastas" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0cf9833681708c7e7bc59aec30f336b1d470a4b79f4163b33f1e6f2619814f4e

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - numpy >=1.10
    - pip
    - python >=3.5
  run:
    - matplotlib-base >=2.0
    - {{ pin_compatible('numpy') }}
    - pandas >=0.22
    - python >=3.5
    - scipy >=1.0

test:
  imports:
    - pastas

about:
  home: https://github.com/pastas/pastas
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Applied System TimeSeries Analysis Software
  doc_url: http://pastas.readthedocs.io
  dev_url: https://github.com/pastas/pastas

extra:
  recipe-maintainers:
    - jentjr
